### ISSUE TITLE
Fails to find existing implementation on Chrome 50 on OSX?

### ISSUE THREAD

**Issue by dagjomar** [mathiasbynens/Array.from#25]
This line
https://github.com/mathiasbynens/Array.from/blob/master/polyfill.js#L18

seems to run fine on Chrome, thus the Polyfill gets added even though Array.from already exsists as a native implementation...?

`Array.from([], undefined);` returns empty array instead of error `[]`

**Comment by ljharb** [comment]
The reason Chrome's implementation is replaced is because `Array.from({ 'length': -Infinity });` throws, rather than properly returning an empty array.
