### ISSUE TITLE
How can I use this in my Angular2 project

### ISSUE THREAD

**Issue by rickysullivan** [mathiasbynens/Array.from#28]
Using systemjs:

`'array.from': 'node_modules/array.from'`

In my .ts file:

`import 'array.from';`

 `Array.from({...})`

Returns this error...

Property 'from' does not exist on type 'ArrayConstructor'.

**Comment by ljharb** [comment]
Per the documentation, you need to `import ArrayFrom from 'array.from'` and then `ArrayFrom.shim()` if you want it installed on the global `Array` method.
