### ISSUE TITLE
Tests results based on latest master

### ISSUE THREAD

**Issue by JakeChampion** [mathiasbynens/Array.from#45]
My IE6/7/8 VMs are having an issue at the moment, could only get tests running for IE 9/10/11.

<details><summary>

Failing:</summary>

- failed: firefox 13 on Windows 10 (8 failed, 116 passed)
- failed: firefox 14 on Linux (8 failed, 116 passed)
- failed: firefox 15 on Mac 10.8 (8 failed, 116 passed)
- failed: firefox 16 on Windows 10 (8 failed, 116 passed)
- failed: firefox 20 on Linux (4 failed, 120 passed)
- failed: firefox 21 on Windows 2012 R2 (4 failed, 120 passed)
- failed: firefox 22 on Windows 10 (4 failed, 120 passed)
- failed: firefox 23 on Windows 2008 (4 failed, 120 passed)
- failed: firefox 24 on Windows 2012 (8 failed, 116 passed)
- failed: firefox 25 on Windows 2012 R2 (8 failed, 116 passed)
- failed: firefox 26 on Windows 2012 R2 (8 failed, 116 passed)
- failed: internet explorer 11 on Windows 10 (8 failed, 116 passed)
  </details>

<details><summary>

Passing:</summary>

- passed: android 4.0 on Linux
- passed: android 4.1 on Linux
- passed: android 4.2 on Linux
- passed: android 4.3 on Linux
- passed: android 4.4 on Linux
- passed: android 5.0 on Linux
- passed: android 5.1 on Linux
- passed: chrome 26 on Windows 2008
- passed: chrome 27 on Windows 2012
- passed: chrome 28 on Windows 2003
- passed: chrome 29 on Linux
- passed: chrome 30 on Windows 2012
- passed: chrome 31 on Windows 2012 R2
- passed: chrome 32 on Windows 2003
- passed: chrome 33 on Mac 10.9
- passed: chrome 34 on Windows 2012 R2
- passed: chrome 35 on Windows 2012 R2
- passed: chrome 36 on Windows 2012
- passed: chrome 37 on Windows 10
- passed: chrome 38 on Windows 2008
- passed: chrome 39 on Windows 10
- passed: chrome 40 on Windows 10
- passed: chrome 41 on Linux
- passed: chrome 42 on Windows 2008
- passed: chrome 43 on Windows 2012 R2
- passed: chrome 44 on Mac 10.9
- passed: chrome 45 on Mac 10.10
- passed: chrome 46 on Linux
- passed: chrome 47 on Windows 2012 R2
- passed: chrome 48 on Windows 10
- passed: chrome 49 on Windows 2003
- passed: chrome 50 on Mac 10.9
- passed: chrome 51 on Windows 2012
- passed: chrome 52 on Windows 2012
- passed: chrome 53 on Mac 10.9
- passed: chrome 54 on Windows 2008
- passed: firefox 10 on Linux
- passed: firefox 11 on Mac 10.8
- passed: firefox 12 on Windows 2003
- passed: firefox 17 on Mac 10.11
- passed: firefox 18 on Windows 10
- passed: firefox 19 on Windows 2003
- passed: firefox 27 on Linux
- passed: firefox 28 on Windows 10
- passed: firefox 29 on Windows 2012 R2
- passed: firefox 30 on Windows 2008
- passed: firefox 31 on Windows 2012 R2
- passed: firefox 32 on Windows 2003
- passed: firefox 33 on Linux
- passed: firefox 34 on Linux
- passed: firefox 35 on Windows 10
- passed: firefox 36 on Windows 2008
- passed: firefox 37 on Windows 2008
- passed: firefox 38 on Mac 10.9
- passed: firefox 39 on Mac 10.9
- passed: firefox 4 on Mac 10.9
- passed: firefox 40 on Mac 10.10
- passed: firefox 41 on Mac 10.8
- passed: firefox 42 on Windows 2003
- passed: firefox 43 on Linux
- passed: firefox 44 on Windows 2008
- passed: firefox 45 on Windows 2008
- passed: firefox 46 on Windows 2008
- passed: firefox 47 on Mac 10.8
- passed: firefox 48 on Mac 10.9
- passed: firefox 49 on Mac 10.11
- passed: firefox 5 on Linux
- passed: firefox 6 on Mac 10.9
- passed: firefox 7 on Mac 10.11
- passed: firefox 8 on Windows 10
- passed: firefox 9 on Linux
- passed: internet explorer 9 on Windows 2008
- passed: internet explorer 10 on Windows 2012
- passed: ipad 8.1 on Mac 10.10
- passed: ipad 8.2 on Mac 10.10
- passed: ipad 8.3 on Mac 10.10
- passed: ipad 8.4 on Mac 10.10
- passed: ipad 9.0 on Mac 10.10
- passed: ipad 9.1 on Mac 10.10
- passed: ipad 9.2 on Mac 10.10
- passed: ipad 9.3 on Mac 10.11
- passed: iphone 8.1 on Mac 10.10
- passed: iphone 8.2 on Mac 10.10
- passed: iphone 8.3 on Mac 10.10
- passed: iphone 8.4 on Mac 10.10
- passed: iphone 9.0 on Mac 10.10
- passed: iphone 9.1 on Mac 10.10
- passed: iphone 9.2 on Mac 10.10
- passed: iphone 9.3 on Mac 10.11
- passed: microsoftedge 13 on Windows 10
- passed: microsoftedge 14 on Windows 10
- passed: opera 11 on Windows 2003
- passed: opera 12 on Windows 2003
- passed: safari 5 on Windows 2008
- passed: safari 6 on Mac 10.8
- passed: safari 7 on Mac 10.9
- passed: safari 8 on Mac 10.10
- passed: safari 9 on Mac 10.11
  </details>

**Comment by ljharb** [comment]
Thanks!
