### ISSUE TITLE
Splits astral symbol into surrogate pairs

### ISSUE THREAD

**Issue by MadLittleMods** [mathiasbynens/Array.from#47]
The polyfill splits each unicode character(astral symbol) into their surrogate pairs while the native implementation keeps them intact.

```js
var arrayFrom = require('array.from');

// ["🖐", "🏿"]
const nativeResult = Array.from('🖐🏿');
// ["�", "�", "�", "�"]
const polyfillResult = arrayFrom('🖐🏿');
console.log(nativeResult, polyfillResult);
```
https://runkit.com/madlittlemods/58aaa693808777001350cf41

---

Relevant issues,

 - https://github.com/mathiasbynens/Array.from/issues/4

**Comment by MadLittleMods** [comment]
This works with the [latest from the repo](https://github.com/mathiasbynens/Array.from/commits/dc211b013ffe2e0877e4e4ea05cd652e8b7e4943).

I suspect https://github.com/mathiasbynens/Array.from/pull/33 fixed things up. Thanks @falsandtru 😀 

@ljharb Friendly ping for timeline on next npm release?

**Comment by ljharb** [comment]
There's a bit of work to do before the master branch is ready for release. It likely won't be super soon.

**Comment by ljharb** [comment]
v1.1.0 is now released which should contain all the latest fixes, and will iterate properly in every version of every engine.
