### ISSUE TITLE
Publish release to npm

### ISSUE THREAD

**Issue by not-an-aardvark** [mathiasbynens/Array.from#49]
A few bugs have been fixed on master since this package was last published to npm, and I ran into [one of them](https://github.com/mathiasbynens/Array.from/issues/4) today via an upstream dependency. When you get the chance, can you publish a new release to npm?

**Comment by ljharb** [comment]
master is currently not tested properly; any release would have to be a very unstable semver-major.

#4 isn't a bug; it's an omitted feature - and that's exactly the one that needs extensive testing before it's released.

**Comment by ljharb** [comment]
(see #41, #45, #44)

**Comment by not-an-aardvark** [comment]
Makes sense, I hadn't realized master was unstable. I'll close this issue then.

**Comment by ljharb** [comment]
v1.1.0 is now released which should contain all the latest fixes, and will iterate properly in every version of every engine.
