### ISSUE TITLE
Object doesn't support property or method 'from'

### ISSUE THREAD

**Issue by shinriyo** [mathiasbynens/Array.from#51]
I installed and `import 'array.from';`
but
` Object doesn't support property or method 'from' ` error.

**Comment by ljharb** [comment]
What code did you get this error on? Note that `Array.from` is a static method; it's on `Array`, but NOT on individual arrays.

Separately, `import 'array.from'` is a no-op. If you want to shim the environment, `import shim from 'array.from/shim'; shim()`.

**Comment by ExE-Boss** [comment]
You need to do:
```js
import "array.from/auto";
```
according to [the latest version of the **es‑shim API**](https://github.com/es-shims/es-shim-api/blob/c17e78e8d245bb925f2b1bf8da505eef0783bcef/README.md#api-contract), which this doesn’t yet implement (see also #53).

**Comment by ljharb** [comment]
v1.1.0 will be released soon which should address any outstanding issues.
